#! /usr/bin/env php


<?php

use Symfony\Component\Console\Application;
require 'vendor/autoload.php';

$app = new Application('Task App', '1.0');



$dbAdapter = new Acme\DatabaseAdapter($pdo);
$app->add(new Acme\ShowCommand);

$app->run();
